### ISSUE TITLE
Nodebb 1.0 Issue

### ISSUE THREAD

**Issue by Holyphoenix** [RestingCoder/nodebb-widget-discord#3]
After activating and adding my widget on global sidebar, my forum crashes for a little bit.  Lots of 502 gateway errors.  It appears to try to load any page for a while, and then goes down.  I was wondering if this could be fixed?  This would be a super useful plugin form me.  Thanks!

**Comment by RestingCoder** [comment]
NodeBB changes too often, and they are constantly saying they will be rewriting the entire plugin/widget system. It has been that way for over a year now. I have created an alternative widget that can be used within an HTML widget on NodeBB instead using this code:

    <script type="text/javascript">
    require(["http://discord.knightsoftheblade.com/discord.min.js"], function () {
    discordWidget.init({
        serverId: '51143782082543616',
        join: true,
        alphabetical: false,
        theme: 'none',
        hideChannels: ['Channel Name 1', 'Channel Name 2'],
        showAllUsers: true,
        allUsersDefaultState: true
      });
      discordWidget.render();
    });
    </script>
    <div class="discord-widget"></div>


Details for the parameters can be found here:  http://discord.deliriousdrunkards.com/
